# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'DMZing' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
pod 'Kingfisher', '~>4.0.0'
pod 'SnapKit', '~>4.0.1'
pod 'SwiftyJSON', '~>4.2.0'
pod 'Alamofire', '~>4.7.3'
pod 'LTScrollView'
  # Pods for DMZing

end
